site_name: My Docs
theme: dracula
use_directory_urls: false

nav:
    - Home: README.md
    - Eines:
      - Atacs_Contrasenyes:
          - Atacs_Offline:
              - Hashcat: eines/Atacs_Contrasenyes/Atacs_Offline/hashcat/hashcat.md
              - John the Ripper: eines/Atacs_Contrasenyes/Atacs_Offline/john_the_ripper/johntheripper.md
          - Atacs_Online:
              - Hydra: eines/Atacs_Contrasenyes/Atacs_Online/hydra/hydra.md
      - Atacs Web:
          - Dirb: eines/Atacs_web/dirb/dirb.md
          - WpScan: eines/Atacs_web/wpscan/wpscan.md
      - Connexio:
          - ncat: eines/Connexio/ncat/ncat.md
          - masscan: eines/Escaneig/masscan/masscan.md
      - Enumeracio:
          - webcopilot: eines/Enumeracio/webcopilot.md
      - Escaneig:
          - masscan: eines/Escaneig/masscan/masscan.md
          - nmap: eines/Escaneig/nmap/nmap.md
      - Privilege_Escalation:
          - PEASS-ng: eines/Privilege_Escalation/PEASS-ng/peass-ng.md
      - Wireless:
          - h4rpy: eines/Wireless/h4rpy/h4rpy.md
    - metodes:
       - reverseShells: metodes/reverseShells.md
       - Kali Reverse Shells: metodes/kaliReverseShells.md
    - Eines Externes:
       - Reverse Shell Generator: einesExternes/reverse-shell-generator/index.html